name: Build and Push Docker Image to Aliyun ACR

on:
  push:
    paths:
      - 'docker-image-name.txt' # 监听此文件的更改

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read Docker Image Name
        id: read_image_name
        run: |
          IMAGE_NAME=$(cat docker-image-name.txt)
          echo "::set-output name=image_name::$IMAGE_NAME"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Aliyun ACR
        uses: docker/login-action@v2
        with:
          registry: crpi-c0zrpotckyt9cc1u.cn-hangzhou.personal.cr.aliyuncs.com # 替换为你的阿里云ACR地址
          username: ${{ secrets.ALIYUN_ACR_USERNAME }} # 替换为你的阿里云ACR用户名secret
          password: ${{ secrets.ALIYUN_ACR_PASSWORD }} # 替换为你的阿里云ACR密码secret

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.read_image_name.outputs.image_name }} # 使用从文件中读取的镜像名称
