name: Download and Rename Files kk
on:
  workflow_dispatch:
jobs:
  download_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download install_lts.sh
        run: |
          curl -o install_lts.sh https://download.bt.cn/install/install_lts.sh
      - name: Download BtSoft.zip
        run: |
          curl -o BtSoft.zip https://download.bt.cn/win/panel/BtSoft.zip
      - name: Upload install_lts.sh
        uses: actions/upload-artifact@v3
        with:
          name: install_lts.sh
          path: install_lts.sh
      - name: Upload BtSoft.zip
        uses: actions/upload-artifact@v3
        with:
          name: BtSoft.zip
          path: BtSoft.zip
