name: baota panel downloader
on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 0 * * *'  # 每天0点触发
jobs:
  download_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download install_lts.sh
        run: |
          curl -o install_lts.sh https://download.bt.cn/install/install_lts.sh
      - name: Download BtSoft.zip
        run: |
          curl -o BtSoft.zip https://download.bt.cn/win/panel/BtSoft.zip
      - name: Upload install_lts.sh
        uses: actions/upload-artifact@v3
        with:
          name: install_lts.sh
          path: install_lts.sh
        uses: softprops/action-gh-release@v2
      with:
        files: |
          linux.sh
          docker_desktop_installer_windows_x86_64.exe
          docker_desktop_installer_mac_arm64.dmg
          docker_desktop_installer_mac_x84_64.dmg
          docker_desktop_installer_linux_debian_x84_64.dmg
          docker_desktop_installer_linux_fedora_x84_64.dmg
        tag_name: latest
      - name: Upload BtSoft.zip
        uses: actions/upload-artifact@v3
        with:
          name: BtSoft.zip
          path: BtSoft.zip
        
