name: Download and Rename Files vm
   on:
     push:
       branches:
         - master
   jobs:
     download_and_rename:
       runs-on: ubuntu-latest
       steps:
         - name: set beijing timezone
           uses: szenius/set-timezone@v1.2 
           with:
             timezoneLinux: "Asia/Shanghai"
         - uses: actions/checkout@v3
         - name: Download install_lts.sh
           run: |
             wget -O $(date +%Y%m%d)_install_lts.sh <mark>https://download.bt.cn/install/install_lts.sh</mark>
         - name: Download BtSoft.zip
           run: |
             wget -O $(date +%Y%m%d)_BtSoft.zip <mark>https://download.bt.cn/win/panel/BtSoft.zip</mark>
