name: baota panel downloader
on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 0 * * *'  # 每天0点触发
jobs:
  download_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download install_lts.sh
        run: |
          curl -o install_lts.sh https://download.bt.cn/install/install_lts.sh
      - name: Download BtSoft.zip
        run: |
          curl -o BtSoft.zip https://download.bt.cn/win/panel/BtSoft.zip
      - name: Upload install_lts.sh
        uses: softprops/action-gh-release@v2
        with:
          files: |
            install_lts.sh
          tag_name: latest
      - name: Upload BtSoft.zip
        uses: softprops/action-gh-release@v2
        with:
          files: |
            BtSoft.zip
          tag_name: latest
