name: baota panel downloader
on:
  
  schedule:
    - cron: '0 1 * * *'  # 每天0点触发
jobs:
  download_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download install_lts.sh
        run: |
          curl -o install_lts.sh https://download.bt.cn/install/install_lts.sh
      - name: Download BtSoft.zip
        run: |
          curl -o BtSoft.zip https://download.bt.cn/win/panel/BtSoft.zip
          curl -o 360setup.exe https://sfdl.360safe.com/inst.exe
      - name: Upload packages
        uses: softprops/action-gh-release@v2
        with:
          files: |
            install_lts.sh
            BtSoft.zip
            360setup.exe
          tag_name: latest
