name: FRP Access
on:
  workflow_dispatch:
jobs:
  access-runner-via-frp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start frp tunnel
        uses: cirunlabs/frp-tunnel-action@v1.2.0
        with:
          timeout_minutes: 5
          frp_server: 'frp.freefrp.net'
          frp_token: 'freefrp.net'
          local_port: 22
          remote_port: 18653