name: FRP Access
on:
  workflow_dispatch:
jobs:
  access-runner-via-frp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start frp tunnel
        uses: cirunlabs/frp-tunnel-action@v1.2.0
        with:
          timeout_minutes: 1
          frp_server: '154.83.95.197'
          frp_token: '${{ secrets.FRP_SERVER_TOKEN }}'
          local_port: 22
          remote_port: 43807