name: Deploy OpenFrp Client

on:
  workflow_dispatch: # 允许手动触发

jobs:
  deploy-frp:
    runs-on: windows-latest # 必须使用 Windows Runner 以运行 .exe

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download OpenFrp
        run: |
          $url = "https://staticassets.naids.com/client/OF_0.67.0_690979b2_260223/frpc_windows_amd64.zip"
          
          Invoke-WebRequest -Uri $url -OutFile "chmlfrp.zip"
          
          # 解压
          Expand-Archive -Path "chmlfrp.zip" -DestinationPath "."

      - name: Start OpenFrp Client
        run: |
          .\frpc_windows_amd64 -u "${{ secrets.FRP_USER }}" -p "${{ secrets.FRP_TOKEN }}"