name: Run Unsigned PowerShell Script

on: workflow_dispatch

jobs:
  run-script:
    runs-on: windows-latest  # 必须使用 Windows 环境
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run b.ps1 with Bypass Policy
        # 方法：直接调用 powershell.exe 并传入 Bypass 参数
        # 这样可以在不改变系统全局策略的情况下运行未签名脚本
        run: powershell -ExecutionPolicy Bypass -File .\b.ps1
        shell: cmd  # 或者使用 'cmd'，显式指定 shell 可以避免默认行为干扰
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-vhd-image
          path: D:\b.vhd